#   The endpoint which clients should query to resolve stellar addresses
#   for users on your domain.
FEDERATION_SERVER="https://api.catcat.io/federation"

# The endpoint used for the compliance protocol
AUTH_SERVER="https://api.catcat.io/auth"

# asset with meta info
[[CURRENCIES]]
code="CAT"
issuer="GBE63C5HALO3LET4FRJ7ICN6E26OYFXIRPYUTNXOP7M752XCLMGPARVZ"
display_decimals=4
name="CAT"
desc="1 CAT token represent 1 cat in the world"
conditions="There will only ever be 600,000,000 CAT tokens in existence."
image="https://avatars1.githubusercontent.com/u/36980416"