#   The endpoint which clients should query to resolve stellar addresses
#   for users on your domain.
FEDERATION_SERVER="https://api.catcat.io/federation"

# The endpoint used for the compliance protocol
AUTH_SERVER="https://api.catcat.io/auth"

# asset with meta info
[[CURRENCIES]]
code="CAT"
issuer="GAPHVTI67DKIHG77R33ADCFZ6KEOPJEEEIOFF47HUMXEMQSQ6KFKXCAT"
display_decimals=4
name="CAT"
desc="1 CAT token represent 1 cat in the world"
conditions="There will be 600,000,000 CAT tokens in existence for now."
image="https://avatars1.githubusercontent.com/u/36980416"